server:
  port: 8086
spring:
  application:
    name: demo2
    #springboot maven项目ESBboss配置文件
  elasticsearch:
    bboss:
      elasticsearch:
        rest:
          hostNames: 127.0.0.1:9200
  kafka:
    bootstrap-servers: 127.0.0.1:9092 #指定kafka server的地址，集群配多个，中间，逗号隔开
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: default_consumer_group #群组ID
      enable-auto-commit: true
      auto-commit-interval: 1000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


  messages:
    basename: i18n/messages
  datasource:
    # TEST环境
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver



#mybatis配置
mybatis:
    mapper-locations: classpath:mapper/**.xml



##springboot maven项目ESBboss配置文件
#spring.elasticsearch.bboss.elasticsearch.rest.hostNames=127.0.0.1:9200

