server:
  port: 8082
spring:
  application:
    name: demo2
  messages:
    basename: i18n/messages
  datasource:
    # TEST环境
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver



#mybatis配置
mybatis:
    mapper-locations: classpath:mapper/**.xml

